spring:
  datasource:
    url: jdbc:h2:mem:wearly;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
<<<<<<< HEAD
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
=======

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET}
>>>>>>> ba4a42a (feat: integrate S3 image upload with presigned URL for clothes API (#8))
